multi:
  wave:
    10: 45
    20: 50
    30: 25
  parts:
    - messageName: Stack11_Temp01_06
      1: Stack11_Temp_06
      2: Stack11_Temp_05
      3: Stack11_Temp_04
      4: Stack11_Temp_03
      5: Stack11_Temp_02
      6: Stack11_Temp_01
    - messageName: Stack10_Temp07_12
      1: Stack10_Temp_12
      2: Stack10_Temp_11
      3: Stack10_Temp_10
      4: Stack10_Temp_09
      5: Stack10_Temp_08
      6: Stack10_Temp_07