waveConfig:
  updateDuration: 
    unit: ms
    duration: 100

  multi:
      signalNoise: 20
      transformType: linear #linear
      wave:
        0: 50
        10: 45
        20: 50
        30: 25
      parts:
        - Message:
          messageName: test
          messageSignals:
            - Stack11_Temp_06
            - Stack11_Temp_03
        - Message:
          messageName: test2
          messageSignals:
            - Stack11_Temp_03
            - Stack11_Temp_04
        